apiVersion: v1
kind: Secret
metadata:
  name: csi-manila-secrets
stringData:
  # Mandatory
  os-authURL: "https://auth.cloud.ovh.net/v3"
  os-region: "GRA11"

  # Openstack authentication
  os-userName: "{{ sharenetwork.manila_username }}"
  os-password: "{{ sharenetwork.manila_password }}"
  os-domainName: "default"
  os-projectName: "{{ sharenetwork.osprojectname }}"
  os-projectDomainID: "default"