apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app: keycloak-operator
  name: keycloak-operator
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: keycloak-operator
  template:
    metadata:
      labels:
        app: keycloak-operator
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_KEYCLOAK_IMAGE
              value: |+
                {{ keycloak.image }}
          image: "{{ keycloak.operator.image }}"
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: keycloak-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: keycloak-operator
