commonLabels:
  app.kubernetes.io/instance: "{{ app_name }}"
namespace: logging

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - daemonset.yaml
  - secret.yaml
  - service-metrics.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
