- name: Deploy reference system
  hosts: kube_control_plane[0]
  remote_user: cloud
  gather_facts: false
  vars_files:
    - "collections/kubespray/roles/kubespray-defaults/defaults/main.yaml"
  roles: 
    - { role: "app-installer" }
