- name: Deploy reference system
  hosts: master[0]
  gather_facts: false
  vars_files:
    - "collections/kubespray/roles/kubespray-defaults/defaults/main.yaml"
  roles: 
    - { role: "app-installer" }
