---
- name: Deploy kubernets with kubespray
  hosts: kube_control_plane[0]
  remote_user: cloud
  tasks:
    - name: Deploy kubernetes
      shell: |
        source ~/miniconda3/bin/activate rspy && \
        sudo mkdir -p /etc/kubernetes && \
        cd ~/rs-infrastructure && \
        source {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/openrc.sh && \
        sed -i 's#{{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/privatekey.pem#/home/cloud/.ssh/privatekey.pem#' {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/hosts.yaml && \
        ansible-playbook collections/kubespray/cluster.yml -i {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/hosts.yaml --become && \
        mkdir -p ~/.kube && sudo cp /etc/kubernetes/admin.conf ~/.kube/config && sudo chown cloud: ~/.kube/config && \
        cd roles/terraform/create-cluster/tasks && source .env && \
        for type in $(terraform output -json hosts | jq -r '.[] | .tags.type' | grep -oh "\w*" | sort | uniq); \
        do $(terraform output -json hosts | jq -r --arg type $type '.[] | select(.tags.type | contains ($type)) | "kubectl label nodes \(.name) node-role.kubernetes.io/\(.tags.type)="' | xargs -I % sh -c 'echo %;'); done
      args:
        executable: /bin/bash
      async: 3600
      poll: 30
