# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Deploy kubernets with kubespray
  hosts: kube_control_plane[0]
  remote_user: cloud
  tasks:
    - name: Deploy kubernetes
      shell: |
        source ~/miniforge3/bin/activate rspy && \
        sudo mkdir -p /etc/kubernetes && \
        cd ~/rs-infrastructure && \
        source {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/openrc.sh && \
        sed -i 's#{{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/privatekey.pem#/home/cloud/.ssh/privatekey.pem#' {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/hosts.yaml && \
        ansible-playbook collections/kubespray/cluster.yml -i {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/hosts.yaml --become && \
        mkdir -p ~/.kube && sudo cp /etc/kubernetes/admin.conf ~/.kube/config && sudo chown cloud: ~/.kube/config && \
        cd roles/terraform/create-cluster/tasks && source .env && \
        terraform output -json hosts | jq -r '.[] | "\(.name),\(.tags.type)"' | while read line ; do kubectl label node ${line%,*} node-role.kubernetes.io/${line#*,}= ; done ;
      args:
        executable: /bin/bash
      async: 3600
      poll: 30
