---
- name: Start the cluster
  hosts: localhost
  roles:
    - { role: "terraform/start" }
  tags: start

- name: Stop the cluster
  hosts: localhost
  roles:
    - { role: "terraform/stop" }
  tags: stop