commonLabels:
  app.kubernetes.io/instance: "{{ app_name }}"
namespace: neuvector


helmCharts:
- name: monitor
  repo: https://neuvector.github.io/neuvector-helm/
  releaseName: "{{ app_name }}"
  version: 5.3
  namespace: neuvector
  valuesFile: values.yaml