apiVersion: batch/v1
kind: Job
metadata:
  name: create-prefect-db
spec:
  ttlSecondsAfterFinished: 360
  template:
    spec:
      containers:
      - name: create-prefect-db
        image: ghcr.io/cloudnative-pg/postgresql:16.1
        command: ["/scripts/create-database.sh"]
        volumeMounts:
          - name: create-database
            mountPath: /scripts/
        env:
        - name: DATABASE
          value: {{ prefect.database.name }}
        - name: PGNEWUSER
          valueFrom:
            secretKeyRef:
              name: {{ prefect.database.secret }}
              key: username
        - name: PGNEWPASS
          valueFrom:
            secretKeyRef:
              name: {{ prefect.database.secret }}
              key: password
        - name: PGADMIN
          valueFrom:
            secretKeyRef:
              name: postgresql-cluster-superuser
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-cluster-superuser
              key: password
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: postgresql-cluster-superuser
              key: host
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: postgresql-cluster-superuser
              key: port
      volumes:
      - name: create-database
        configMap:
          name: create-database
          defaultMode: 0744
      restartPolicy: Never

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ prefect.database.secret }}
  labels: 
    app: prefect
type: Opaque
stringData:
  username: {{ prefect.database.username }}
  password: {{ prefect.database.password }}