# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Create override.tfvars
  shell: |
    sed -E 's/(desired_nodes = )[0-9]+/\10/g' {{ inventory_dir }}/cluster.tfvars | sed -E 's/(autoscale = )[a-z]+/\1false/g' > {{ inventory_dir }}/override.tfvars
  args:
    chdir: roles/terraform/cluster/tasks/
    executable: /bin/bash

- name: Stop cluster
  shell: |
    set -o allexport; source {{ inventory_dir }}/.env; source {{ inventory_dir }}/openrc.sh; set +o allexport; terraform apply -auto-approve -var-file="{{ inventory_dir }}/override.tfvars" \
      -target=ovh_cloud_project_kube_nodepool.nodepool_infra \
      -target=ovh_cloud_project_kube_nodepool.nodepool_rs_server \
      -target=ovh_cloud_project_kube_nodepool.nodepool_rs_env \
      -target=ovh_cloud_project_kube_nodepool.nodepool_access_csc \
      -target=ovh_cloud_project_kube_nodepool.nodepool_prefect_flow \
      -target=ovh_cloud_project_kube_nodepool.nodepool_dask_scheduler \
      -target=ovh_cloud_project_kube_nodepool.nodepool_dask_worker_on_demand && \
      rm {{ inventory_dir }}/override.tfvars
  args:
    chdir: roles/terraform/cluster/tasks/
    executable: /bin/bash
