{{- if ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels: keycloak
spec:
  ingressClassName: nginx
  rules:
  - host: iam.{{ platform_domain_name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-service
            port:
              number: 8080
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
  {{- if .Values.ingress.tls }}
  - hosts:
    - iam.{{ platform_domain_name }}
    secretName: iam-{{ platform_domain_name | replace(".", "-") }}
  {{- end }}
  {{- end }}
{{- end }}
