apiVersion: v1
kind: Secret
metadata:
  name: {{ keycloak.database.secret }}
  labels: 
    app: keycloak
type: Opaque
stringData:
  username: {{ keycloak.database.username }}
  password: {{ keycloak.database.password }}
