# Copyright 2023-2025 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


resources:
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/backuprepositories.yaml
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/backups.yaml
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/backupstoragelocations.yaml
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/datadownloads.yaml
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/datauploads.yaml
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/deletebackuprequests.yaml
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/downloadrequests.yaml
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/podvolumebackups.yaml
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/podvolumerestores.yaml
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/restores.yaml
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/schedules.yaml
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/serverstatusrequests.yaml
- https://raw.githubusercontent.com/vmware-tanzu/helm-charts/refs/tags/velero-7.1.0/charts/velero/crds/volumesnapshotlocations.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: '{{ app_name }}'
