apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup-pvc-wazuh-manager
  namespace: infra
spec:
  includedNamespaces:
    - security
  includedResources:
    - persistentvolumeclaims
    - persistentvolumes
  labelSelector:
    matchLabels:
      app: wazuh-manager
  storageLocation: {{ velero.bckStorageLoc.name }}
  ttl: 72h
---
apiVersion: velero.io/v1
kind: Backup
metadata:
  name: backup-wazuh-indexer
  namespace: infra
spec:
  includedNamespaces:
    - security
  includedResources:
    - persistentvolumeclaims
    - persistentvolumes
  labelSelector:
    matchLabels:
      app: wazuh-indexer
  storageLocation: {{ velero.bckStorageLoc.name }}
  ttl: 72h