apiVersion: velero.io/v1
kind: Restore
metadata:
  name: restore-pvc-grafana
  namespace: infra
spec:
  backupName: backup-pvc-grafana
  includedNamespaces:
    - monitoring
  includedResources:
    - persistentvolumeclaims
    - persistentvolumes