apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: schedule-backup-wazuh-manager
  namespace: infra
spec:  
  schedule: "0 12 * * *"
  template:
    ttl: 240h
    includedNamespaces:
      - security
    labelSelector:
      matchLabels:
        app: wazuh-manager
        backup: opt-in
    snapshotVolumes: true
    storageLocation: {{ velero.bckStorageLoc.name }}
    volumeSnapshotLocations:
      - aws-default
---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: schedule-backup-wazuh-indexer
  namespace: infra
spec:  
  schedule: "0 12 * * *"
  template:
    ttl: 240h
    includedNamespaces:
      - security
    labelSelector:
      matchLabels:
        app: wazuh-indexer
        backup: opt-in
    snapshotVolumes: true
    storageLocation: {{ velero.bckStorageLoc.name }}
    volumeSnapshotLocations:
      - aws-default