# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Set CI mode flag with a default (can be overridden via -e private_registry=true)
- name: Use managed private docker registry (default false)
  set_fact:
    private_registry: "{{ (private_registry | default(false)) | bool }}"

- name: Install app
  block:
    - name: "{{ package_name }} - {{ app_name }} | Check whether kustomization.yaml file exists"
      stat:
        path: "{{ app_dir }}/kustomization.yaml"
      delegate_to: bastion
      register: kustomization_file

    - name: "{{ package_name }} - {{ app_name }} | Fail if no kustomization file found"
      fail:
        msg: "No kustomization.yaml file found in {{ app_dir }}. Documentation available at https://github.com/RS-PYTHON/rs-infra-core/blob/develop/docs/installation.md"
      when: not kustomization_file.stat.exists

    - name: "{{ package_name }} - {{ app_name }} | Include vars from kustomization.yaml"
      include_vars:
        file: "{{ app_dir }}/kustomization.yaml"
        name: kustomization
      delegate_to: bastion

    - name: "{{ package_name  }} - {{ app_name }} | Check whether .helm_repository_config.yaml exists"
      stat:
        path: "{{ app_dir }}/.helm_repository_config.yaml"
      register: repository_config
      delegate_to: bastion

    - name: "{{ package_name  }} - {{ app_name }} | Include vars from .helm_repository_config.yaml"
      include_vars:
        file: "{{ app_dir }}/.helm_repository_config.yaml"
      when: repository_config.stat.exists
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Create tmp directory for k8s resources"
      tempfile:
        state: directory
        suffix: "k8s_resources_{{ app_name }}"
      register: resources_dir
      delegate_to: bastion
      check_mode: false

    - name: "{{ package_name }} - {{ app_name }} | Template and send resources to remote"
      template:
        src: "{{ item }}"
        dest: "{{ resources_dir.path }}/{{ item | basename }}"
      with_fileglob: "{{ app_dir }}/*"
      when:
        - item not in ['.helm_repository_config.yaml', 'resources.txt']
      delegate_to: bastion
      check_mode: false

    - name: "{{ package_name }} - {{ app_name }} | Copy subdirectories to remote"
      copy:
        src: "{{ app_dir }}/{{ item.path }}"
        dest: "{{ resources_dir.path }}"
      with_community.general.filetree: "{{ app_dir }}/"
      when:
        - item.state == 'directory'
      delegate_to: bastion
      check_mode: false

    - name: "{{ package_name }} - {{ app_name }} | Pull charts from private repositories"
      shell: |
        helm pull \
        --untar --untardir {{ resources_dir.path }}/charts \
        --repo {{ item.0.repo }} {{ item.0.name }} \
        {{ "--version " + item.0.version if item.0.version is defined else omit }} \
        {{ "--username " + item.1.username if item.1.username is defined else omit }} \
        {{ "--password " + item.1.password if item.1.password is defined else omit }}
      loop: "{{ kustomization.helmCharts | product(helm_repositories) }}"
      when:
        - repository_config.stat.exists
        - helm_repositories is defined
        - kustomization.helmCharts is defined
        - item.0.repo == item.1.name
      delegate_to: bastion
      check_mode: false

    - name: "{{ package_name }} - {{ app_name }} | Deploy resources"
      shell: |
        kustomize build --enable-helm {{ resources_dir.path }} \
        {% if private_registry | bool %} \
        | sed -E '/image:/ {
          /image: (docker.io\/)?([a-z0-9\-]+\/[a-z0-9\-]+)(:[^@ ]+)?(@sha256:[a-f0-9]{64})?/ {
            s|image: (docker.io\/)?([a-z0-9\-]+\/[a-z0-9\-]+)(:[^@ ]+)?(@sha256:[a-f0-9]{64})?|image: {{ registry.harbor_url | regex_replace('^https?://', '') }}/proxycache/\2\3\4|
            b
          }
          /image: ([a-z0-9\-]+\/[a-z0-9\-]+)(:[^@ ]+)?(@sha256:[a-f0-9]{64})?/ {
            s|image: ([a-z0-9\-]+\/[a-z0-9\-]+)(:[^@ ]+)?(@sha256:[a-f0-9]{64})?|image: {{ registry.harbor_url | regex_replace('^https?://', '') }}/proxycache/\1\2\3|
            b
          }
          /image: ([a-z0-9\-]+)(:[^@ ]+)?(@sha256:[a-f0-9]{64})?/ {
            s|image: ([a-z0-9\-]+)(:[^@ ]+)?(@sha256:[a-f0-9]{64})?|image: {{ registry.harbor_url | regex_replace('^https?://', '') }}/proxycache/\1\2\3|
          }
        }' \
        | yq eval 'select(.kind == "Pod") |= .spec.imagePullSecrets += [{"name": "harbor-pull-secret"}] |
            select(.kind == "Deployment") |= .spec.template.spec.imagePullSecrets += [{"name": "harbor-pull-secret"}] |
            select(.kind == "StatefulSet") |= .spec.template.spec.imagePullSecrets += [{"name": "harbor-pull-secret"}] |
            select(.kind == "DaemonSet") |= .spec.template.spec.imagePullSecrets += [{"name": "harbor-pull-secret"}] |
            select(.kind == "Job") |= .spec.template.spec.imagePullSecrets += [{"name": "harbor-pull-secret"}] |
            select(.kind == "CronJob") |= .spec.jobTemplate.spec.template.spec.imagePullSecrets += [{"name": "harbor-pull-secret"}] |
            select(.kind == "ReplicaSet") |= .spec.template.spec.imagePullSecrets += [{"name": "harbor-pull-secret"}]' - \
        {% endif %} \
        | kubectl apply -f - \
        {% if ansible_check_mode and not app_name.startswith('crds') and app_name != 'namespaces' %} \
          --dry-run=server \
        {% endif %} \
        --server-side \
        --force-conflicts \
        -l app.kubernetes.io/instance={{ app_name }}
      register: result
      delegate_to: bastion
      check_mode: false

    - name: "{{ package_name }} - {{ app_name }} | reset facts"
      set_fact:
        resources: []
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Extract deployed resources"
      set_fact:
        resources: "{{ resources|d([]) + [item.split()[0]] }}"
      loop: "{{ result.stdout_lines }}"
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Collect deployed resources and write them into resources.txt"
      copy:
        content: "{{ resources | join(' ') }}"
        dest: "{{ app_dir }}/resources.txt"
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Detect jobs for this app"
      kubernetes.core.k8s_info:
        kind: Job
        label_selectors:
          - "app.kubernetes.io/instance = {{ app_name }}"
      register: jobs
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Wait until jobs are complete (if any)"
      kubernetes.core.k8s_info:
        kind: Job
        label_selectors:
          - "app.kubernetes.io/instance = {{ app_name }}"
        wait: true
        wait_sleep: 1
        wait_timeout: 120
        wait_condition:
          type: Complete
      when: jobs.resources | length > 0
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Detect pods for this app"
      kubernetes.core.k8s_info:
        kind: Pod
        label_selectors:
          - "!job-name"
          - "app.kubernetes.io/instance={{ app_name }}"
      register: pods
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Wait until pods are ready (if any)"
      kubernetes.core.k8s_info:
        kind: Pod
        label_selectors:
          - "!job-name"
          - "app.kubernetes.io/instance={{ app_name }}"
        wait: true
        wait_sleep: 1
        wait_timeout: 120
      when: pods.resources | length > 0
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Detect deployments for this app"
      kubernetes.core.k8s_info:
        kind: Deployment
        label_selectors:
          - "app.kubernetes.io/instance = {{ app_name }}"
      register: deployments
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Wait until deployments are ready (if any)"
      kubernetes.core.k8s_info:
        kind: Deployment
        label_selectors:
          - "app.kubernetes.io/instance = {{ app_name }}"
        wait: true
        wait_sleep: 1
        wait_timeout: 120
      when: deployments.resources | length > 0
      delegate_to: bastion

  rescue:
    - name: "{{ package_name }} - {{ app_name }} | Show jobs status"
      debug:
        var: jobs.resources
      when: jobs.resources | length > 0

    - name: "{{ package_name }} - {{ app_name }} | Get logs of each job"
      kubernetes.core.k8s_log:
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
        all_containers: true
      loop: "{{ jobs.resources }}"
      when: jobs.resources | length > 0
      ignore_errors: true
      register: job_logs
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Show jobs logs"
      debug:
        var: job_logs
      when: jobs.resources | length > 0

    - name: "{{ package_name }} - {{ app_name }} | Show pods status"
      debug:
        var: pods.resources
      when: pods.resources | length > 0

    - name: "{{ package_name }} - {{ app_name }} | Get logs of each pod"
      kubernetes.core.k8s_log:
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
        all_containers: true
      loop: "{{ pods.resources }}"
      when: pods.resources | length > 0
      ignore_errors: true
      register: pod_logs
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Show pods logs"
      debug:
        var: pod_logs
      when: pods.resources | length > 0

    - name: "{{ package_name }} - {{ app_name }} | Show deployments status"
      debug:
        var: deployments.resources
      when: deployments.resources | length > 0

    - name: "{{ package_name }} - {{ app_name }} | Get logs of each deployment"
      kubernetes.core.k8s_log:
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
        all_containers: true
      loop: "{{ deployments.resources }}"
      when: deployments.resources | length > 0
      ignore_errors: true
      register: deployment_logs
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Show deployments logs"
      debug:
        var: deployment_logs
      when: deployments.resources | length > 0

    - name: "{{ package_name }} - {{ app_name }} | Fail the playbook"
      fail:
        msg: "Deployment {{ app_name }} failed! See debug info above."

  always:
    - name: "{{ package_name }} - {{ app_name }} | Remove resources tmp dir"
      file:
        path: "{{ resources_dir.path }}"
        state: absent
      when:
        - resources_dir.path is defined
        - not debug
      delegate_to: bastion

    - name: "{{ package_name }} - {{ app_name }} | Warn about not deleted tmp folder"
      debug:
        msg:
          - "DEBUG: the temporary folder containing the k8s resources has been kept for debugging purpose"
          - "{{ resources_dir.path }}"
          - "DO NOT FORGET TO DELETE IT WHEN YOU ARE DONE"
      when:
        - debug
      delegate_to: bastion
