package_paths:
- apps

platform_domain_name: rspy.example.com

# TODO:
# Clean unused secrets here and in realmimport 
grafana_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
graylog_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
kibana-processing_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
kibana-security_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
kubectl_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
linkerd_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
prometheus_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
thanos_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
oauth2-proxy_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
# https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/#generating-a-cookie-secret
oauth2-proxy_cookieSecret: "sexajn29g-NLZ9CAHGw2E-tbY4c7uKOI6mNIE78UTg4="

certmanager:
  clusterissuer:
    acme:
      email: user@example.com

postgresql:
  postgres_user:
    password: "tmp_password"
  replication_password: "tmp_replication_password"
  replication_user: "tmp_replication_user"

keycloak:
  image: quay.io/keycloak/keycloak:23.0.6
  operator:
    image: quay.io/keycloak/keycloak-operator:23.0.6
  database: 
    host: postgresql-cluster-rw.database.svc.cluster.local
    name: keycloak
    username: keycloak
    password: "tmp_db_password_for_keycloak"
    secret: keycloak-database-password
  serviceMonitor:
    interval: 30s
    scrapeTimeout: 10s
  replicaCount: 1
  proxy:
    mode: passthrough
  logLevel: info

prefect:
  database:
    host: postgresql-cluster-rw.database.svc.cluster.local
    username: prefect
    password: "tmp_db_password_for_prefect"
    name: prefect
