commonLabels:
  app.kubernetes.io/instance: "{{ app_name }}"

namespace: processing

helmCharts:
- name: jupyterhub
  namespace: processing
  repo: https://hub.jupyter.org/helm-chart/
  releaseName: "{{ app_name }}"
  version: 3.3.6
  valuesFile: values.yaml
