---
- name: Start cluster
  shell: |
    set -o allexport; source {{ inventory_dir }}/openrc.sh; source .env; set +o allexport; openstack server start $(terraform output -json hosts | jq -r .[].name)
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash