apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
spec:
  instances: 3

  bootstrap:
    initdb:
      database: {{ keycloak.database.name }}
      owner: {{ keycloak.database.username }}
      secret:
        name: {{ keycloak.database.secret }}

  storage:
    storageClass: csi-cinder-sc-retain
    size: 30Gi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/infra"
              operator: Exists