apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
spec:
  instances: 3

  bootstrap:
    initdb:
      database: {{ keycloak.database.name }}
      owner: {{ keycloak.database.username }}
      secret:
        name: {{ keycloak.database.secret }}
      postInitSQL:
        - create user {{ prefect.database.username }} with encrypted password '{{ prefect.database.password }}';
        - create database {{ prefect.database.name }};
        - grant all privileges on database {{ prefect.database.name }} to {{ prefect.database.username }};
        - alter database {{ prefect.database.name }} owner to {{ prefect.database.username }};

  storage:
    storageClass: csi-cinder-sc-retain
    size: 30Gi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/infra"
              operator: Exists