---
kind: ConfigMap
metadata:
  name: create-database
apiVersion: v1
data:
  create-database.sh: |-
    #!/bin/bash
    
    echo "Create database ..."
    PGPASSWORD=${PGPASSWORD} psql -h ${PGHOST} -p ${PGPORT} -U ${PGADMIN} postgres -c "create user ${PGNEWUSER} with encrypted password '${PGNEWPASS}'" ;
    PGPASSWORD=${PGPASSWORD} psql -h ${PGHOST} -p ${PGPORT} -U ${PGADMIN} postgres -c "create database ${DATABASE}" ;
    PGPASSWORD=${PGPASSWORD} psql -h ${PGHOST} -p ${PGPORT} -U ${PGADMIN} postgres -c "grant all privileges on database ${DATABASE} to ${PGNEWUSER}" ;
    PGPASSWORD=${PGPASSWORD} psql -h ${PGHOST} -p ${PGPORT} -U ${PGADMIN} postgres -c "alter database ${DATABASE} owner to ${PGNEWUSER}" ;