commonLabels:
  app.kubernetes.io/instance: "{{ app_name }}"

namespace: database

helmCharts:
  - name: cloudnative-pg
    repo: https://cloudnative-pg.io/charts/
    version: 0.20.1
    valuesFile: values.yaml
    releaseName: "{{ app_name }}"
    namespace: database

resources:
  - cluster.yaml
  - configmap-create-database.yaml
