# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

- name: Check if ssh_key exists
  stat: 
    path: "{{ inventory_dir }}/privatekey.pem"
  register: privatekey

- name: Create ssh key
  shell: |
    ssh-keygen -b 2048 -t rsa -m PEM -N "" -f {{ inventory_dir }}/privatekey.pem;\
    echo -e "$(grep -v "public_key" {{ inventory_dir }}/cluster.tfvars)\npublic_key = \"$(ssh-keygen -f {{ inventory_dir }}/privatekey.pem -y)\"" > {{ inventory_dir }}/cluster.tfvars
  when: privatekey.stat.exists == False
  args:
    executable: /bin/bash

- name: Create terraform state bucket
  shell: |
    pip install s3cmd==2.4.0 -q -q -q && \
    set -o allexport; source .env; set +o allexport && \
    cat <<EOF > {{ inventory_dir }}/s3cfg
    host_base=https://$(grep endpoint {{ inventory_dir }}/backend.tfvars | cut -d '"' -f 2 | cut -d '/' -f 3)
    host_bucket=https://%(bucket).$(grep endpoint {{ inventory_dir }}/backend.tfvars | cut -d '"' -f 2 | cut -d '/' -f 3)
    access_key=${AWS_ACCESS_KEY_ID}
    secret_key=${AWS_SECRET_ACCESS_KEY}
    use_https=True
    EOF
    $CONDA_PREFIX/bin/s3cmd -c {{ inventory_dir }}/s3cfg mb s3://$(grep "bucket =" {{ inventory_dir }}/backend.tfvars | cut -d '"' -f 2) && \
    rm {{ inventory_dir }}/s3cfg && \
    pip uninstall s3cmd==2.4.0 --yes -q -q -q
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash

- name: Terraform init
  shell: |
    set -o allexport; source .env; set +o allexport; \
    terraform init -upgrade -backend-config="{{ inventory_dir }}/backend.tfvars"
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash

- name: Create terraform cluster
  shell: |
    set -o allexport; source .env; set +o allexport; \
    terraform apply -auto-approve -var-file="{{ inventory_dir }}/cluster.tfvars" -target=module.create-cluster
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash

- name: Create buckets
  shell: |
    set -o allexport; source .env; set +o allexport; \
    terraform apply -auto-approve -var-file="{{ inventory_dir }}/cluster.tfvars" -target=module.create-buckets  
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash

- name: Copy ssh key
  shell: |
    sleep 30 && \
    set -o allexport; source .env; set +o allexport && \
    scp -o StrictHostKeyChecking=no -i {{ inventory_dir }}/privatekey.pem {{ inventory_dir }}/privatekey.pem cloud@$(terraform output eip_addr | sed 's/\"//g'):/home/cloud/.ssh/privatekey.pem && \
    ssh -o StrictHostKeyChecking=no -i {{ inventory_dir }}/privatekey.pem cloud@$(terraform output eip_addr | sed 's/\"//g') chmod 600 /home/cloud/.ssh/privatekey.pem
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash

- name: Update hosts
  shell: |
    set -o allexport; source .env; set +o allexport && \
    cat <<EOF > {{ inventory_dir }}/hosts.yaml
    all:
      hosts:
        setup:
          ansible_connection: local
          ansible_host: 127.0.0.1
        localhost:
          ansible_connection: local
          ansible_host: 127.0.0.1
    EOF
    cat <<EOF >> {{ inventory_dir }}/hosts.yaml
    $(terraform output -json hosts | jq -r '
      .[] | 
      "    \(.name):\n" +
      "      ansible_host: \(.access_ip_v4)\n" +
      "      ansible_ssh_private_key_file: \"/home/cloud/.ssh/privatekey.pem\"\n" +
      "      provider_id: \(.id)"')
    EOF
    sed -i "/master-0/,/ansible_ssh_private_key_file/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/$(terraform output eip_addr | tr -d '\"')/" {{ inventory_dir }}/hosts.yaml && \
    echo "  children:" >> {{ inventory_dir }}/hosts.yaml
    for k8s_role in $(terraform output -json hosts | jq -r '.[] | .tags.k8s_roles' | grep -oh "\w*" | sort | uniq); do
      cat <<EOF >> {{ inventory_dir }}/hosts.yaml
        $k8s_role:
          hosts:
    EOF
      terraform output -json hosts | jq -r --arg k8s_role $k8s_role '.[] | select(.tags.k8s_roles | contains ($k8s_role)) | "        \(.name):"' >> {{ inventory_dir }}/hosts.yaml
      cat <<EOF >> {{ inventory_dir }}/hosts.yaml
          vars:
            nodegroup: $k8s_role
    EOF
      if [[ $(terraform output -json hosts | jq -r --arg k8s_role $k8s_role '.[] | select(.tags.k8s_roles | contains ($k8s_role)) | .metadata.node_labels') ]]; then
        cat <<EOF >> {{ inventory_dir }}/hosts.yaml
            node_labels:
    $(terraform output -json hosts | jq -r --arg k8s_role $k8s_role '.[] | select(.tags.k8s_roles | contains ($k8s_role)) | .metadata.node_labels' | tr ';' '\n' | sed 's/^/          /' | sort | uniq )
    EOF
      fi
      if [[ $(terraform output -json hosts | jq -r --arg k8s_role $k8s_role '.[] | select(.tags.k8s_roles | contains ($k8s_role)) | .metadata.node_taints') ]]; then
        cat <<EOF >> {{ inventory_dir }}/hosts.yaml
            node_taints:
    $(terraform output -json hosts | jq -r --arg k8s_role $k8s_role '.[] | select(.tags.k8s_roles | contains ($k8s_role)) | .metadata.node_taints' | tr ';' '\n' | sed 's/^/          - /' | sort | uniq )
    EOF
      fi
    done
    cat <<EOF >> {{ inventory_dir }}/hosts.yaml
        kube_node:
          hosts:
    $(terraform output -json hosts | jq -r '.[] | select(.name | contains("master") | not) | "        \(.name):"')
    EOF
    cat <<EOF >> {{ inventory_dir }}/hosts.yaml
        k8s_cluster:
          children:
    EOF

    terraform output -json hosts | jq -r '.[] | .tags.k8s_roles' | grep -oh "\w*" | sort | uniq | while read -r role; do
      cat <<EOL >> {{ inventory_dir }}/hosts.yaml
            $role:
    EOL
    done
    cat <<EOF >> {{ inventory_dir }}/hosts.yaml
        calico_rr:
          hosts: {}
    EOF
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash

- name: Create archive
  shell: |
    tar -czf rs-infrastructure.tar.gz -C {{ playbook_dir }} ansible.cfg .gitmodules apps.yaml rs-setup.yaml {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/hosts.yaml {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/openrc.sh {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/host_vars/setup/ {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/group_vars/all/generated_inventory_vars.yaml collections/kubespray roles/

- name: Change ssh key path on localhost
  ansible.builtin.replace:
    path: "{{ inventory_dir }}/hosts.yaml"
    after: 'master-0'
    before: 'provider_id'
    regexp: '\/home\/cloud\/.ssh'
    replace: "{{ inventory_dir }}"

- name: Setup ansible env
  shell: |
    set -o allexport; source .env; set +o allexport && \
    scp -o StrictHostKeyChecking=no -i {{ inventory_dir }}/privatekey.pem {{ playbook_dir }}/rs-infrastructure.tar.gz cloud@$(terraform output eip_addr | sed 's/\"//g'):/home/cloud/ && \
    ssh -o StrictHostKeyChecking=no -i {{ inventory_dir }}/privatekey.pem cloud@$(terraform output eip_addr | sed 's/\"//g') '\
    mkdir -p ~/rs-infrastructure && cd ~/rs-infrastructure && tar -xzf ~/rs-infrastructure.tar.gz && \
    mkdir -p ~/miniforge3 && wget -q https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh -O ~/miniforge3/miniforge.sh && \
    bash ~/miniforge3/miniforge.sh -b -u -p ~/miniforge3 && rm -rf ~/miniforge3/miniforge.sh && ~/miniforge3/bin/conda init bash && \
    echo "roles_path = /home/cloud/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/cloud/rs-infrastructure/collections/kubespray/roles" >> ~/rs-infrastructure/ansible.cfg && \
    sed -i "/master-0/,/ansible_ssh_private_key_file/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/$(hostname -I)/" ~/rs-infrastructure/{{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/hosts.yaml && \
    sed -i "s/OS_DOMAIN_NAME/OS_USER_DOMAIN_NAME/" ~/rs-infrastructure/{{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/openrc.sh && \
    echo -e "cinder_topology_zones :\n  - eu-west-0" >> ~/rs-infrastructure/collections/kubespray/roles/kubespray-defaults/defaults/main/main.yml && \
    cd ~/rs-infrastructure && ~/miniforge3/bin/conda create -y -n rspy python=3.11' && \
    ssh -o StrictHostKeyChecking=no -i {{ inventory_dir }}/privatekey.pem cloud@$(terraform output eip_addr | sed 's/\"//g') '\
    source ~/miniforge3/bin/activate rspy && \
    pip install -U pyOpenSSL ecdsa -r ~/rs-infrastructure/collections/kubespray/requirements.txt && \
    cd ~/rs-infrastructure; ansible-galaxy collection install kubernetes.core openstack.cloud && \
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh && \
    curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash && sudo mv ./kustomize /usr/local/bin/ && \
    wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list && \
    sudo apt update && sudo apt install terraform jq -y
    '
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash
