---
- name: Check if ssh_key exists
  stat: 
    path: "{{ inventory_dir }}/privatekey.pem"
  register: privatekey

- name: Create ssh key
  shell: |
    ssh-keygen -b 2048 -t rsa -m PEM -N "" -f {{ inventory_dir }}/privatekey.pem;\
    echo -e "$(grep -v "public_key" {{ inventory_dir }}/cluster.tfvars)\npublic_key = \"$(ssh-keygen -f {{ inventory_dir }}/privatekey.pem -y)\"" > {{ inventory_dir }}/cluster.tfvars
  when: privatekey.stat.exists == False
  args:
    executable: /bin/bash

- name: Terraform init
  shell: |
    set -o allexport; source .env; set +o allexport; terraform init -upgrade -backend-config="{{ inventory_dir }}/cluster.tfvars"
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash

- name: Create terraform cluster
  shell: |
    set -o allexport; source .env; set +o allexport; terraform apply -auto-approve -var-file="{{ inventory_dir }}/cluster.tfvars" -target=module.create-cluster
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash

- name: Create buckets
  shell: |
    set -o allexport; source .env; set +o allexport; terraform apply -auto-approve -var-file="{{ inventory_dir }}/cluster.tfvars" -target=module.create-buckets  
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash

- name: Copy ssh key
  shell: |
    sleep 30 && \
    set -o allexport; source .env; set +o allexport && \
    scp -o StrictHostKeyChecking=no -i {{ inventory_dir }}/privatekey.pem {{ inventory_dir }}/privatekey.pem cloud@$(terraform output eip_addr | sed 's/\"//g'):/home/cloud/.ssh/privatekey.pem && \
    ssh -o StrictHostKeyChecking=no -i {{ inventory_dir }}/privatekey.pem cloud@$(terraform output eip_addr | sed 's/\"//g') chmod 600 /home/cloud/.ssh/privatekey.pem
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash

- name: Update hosts
  shell: |
    set -o allexport; source .env; set +o allexport && \
    echo -e "all:\n\thosts:\n\t\tsetup:\n\t\t\tansible_connection: local\n\t\t\tansible_host: 127.0.0.1\n\t\tlocalhost:\n\t\t\tansible_connection: local\n\t\t\tansible_host: 127.0.0.1" > {{ inventory_dir }}/hosts.yaml && \
    terraform output -json hosts | jq -r '.[] | "\t\t\(.name):\n\t\t\tansible_host: \(.access_ip_v4)\n\t\t\tansible_ssh_private_key_file: \"\/home\/cloud\/.ssh\/privatekey.pem\"\n\t\t\tprovider_id: \(.id)"' >> {{ inventory_dir }}/hosts.yaml && \
    cat {{ inventory_dir }}/hosts.yaml | sed "/master-0/,/ansible_ssh_private_key_file/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/$(terraform output eip_addr | tr -d '\"')/" > {{ inventory_dir }}/hosts.yaml && \
    echo -e "\tchildren:" >> {{ inventory_dir }}/hosts.yaml; for k8s_role in $(terraform output -json hosts | jq -r '.[] | .tags.k8s_roles' | grep -oh "\w*" | sort | uniq); do echo -e "\t\t$k8s_role:\n\t\t\thosts:" >> {{ inventory_dir }}/hosts.yaml; \
    terraform output -json hosts | jq -r --arg k8s_role $k8s_role '.[] | select(.tags.k8s_roles | contains ($k8s_role)) | "\t\t\t\t\(.name):"' >> {{ inventory_dir }}/hosts.yaml; done && \
    echo -e "\t\tkube_node:\n\t\t\thosts:\n$(terraform output -json hosts | jq -r '.[] | "\t\t\t\t\(.name):"')" >> {{ inventory_dir }}/hosts.yaml && \
    echo -e "\t\tk8s_cluster:\n\t\t\tchildren:\n$(terraform output -json hosts | jq -r '.[] | "\(.tags.k8s_roles)"' | grep -oh "\w*" | sort | uniq | awk '{print "\t\t\t\t"$1":"}')" >> {{ inventory_dir }}/hosts.yaml && \
    echo -e "\t\tcalico_rr:\n\t\t\thosts: {}" >> {{ inventory_dir }}/hosts.yaml && \
    sed -i 's/\t/  /g' {{ inventory_dir }}/hosts.yaml
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash

- name: Create archive
  shell: |
    tar -czf rs-infrastructure.tar.gz -C {{ playbook_dir }} ansible.cfg .gitmodules apps.yaml rs-setup.yaml {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/hosts.yaml {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/openrc.sh {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/group_vars/  {{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/group_vars/all/kubespray.yaml collections/kubespray roles/

- name: Change ssh key path on localhost
  ansible.builtin.replace:
    path: "{{ inventory_dir }}/hosts.yaml"
    after: 'master-0'
    before: 'provider_id'
    regexp: '\/home\/cloud\/.ssh'
    replace: "{{ inventory_dir }}"

- name: Setup ansible env
  shell: |
    set -o allexport; source .env; set +o allexport && \
    scp -o StrictHostKeyChecking=no -i {{ inventory_dir }}/privatekey.pem {{ playbook_dir }}/rs-infrastructure.tar.gz cloud@$(terraform output eip_addr | sed 's/\"//g'):/home/cloud/ && \
    ssh -o StrictHostKeyChecking=no -i {{ inventory_dir }}/privatekey.pem cloud@$(terraform output eip_addr | sed 's/\"//g') '\
    mkdir -p ~/rs-infrastructure && cd ~/rs-infrastructure && tar -xzf ~/rs-infrastructure.tar.gz && \
    mkdir -p ~/miniforge3 && wget -q https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh -O ~/miniforge3/miniforge.sh && \
    bash ~/miniforge3/miniforge.sh -b -u -p ~/miniforge3 && rm -rf ~/miniforge3/miniforge.sh && ~/miniforge3/bin/conda init bash && \
    echo "roles_path = /home/cloud/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/cloud/rs-infrastructure/collections/kubespray/roles" >> ~/rs-infrastructure/ansible.cfg && \
    sed -i "/master-0/,/ansible_ssh_private_key_file/ s/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/$(hostname -I)/" ~/rs-infrastructure/{{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/hosts.yaml && \
    sed -i "s/OS_DOMAIN_NAME/OS_USER_DOMAIN_NAME/" ~/rs-infrastructure/{{ inventory_dir | regex_replace(playbook_dir,'') | replace('/','',1) }}/openrc.sh && \
    echo -e "cinder_topology_zones :\n  - eu-west-0" >> ~/rs-infrastructure/collections/kubespray/roles/kubespray-defaults/defaults/main.yaml && \
    cd ~/rs-infrastructure && ~/miniforge3/bin/conda create -y -n rspy python=3.11' && \
    ssh -o StrictHostKeyChecking=no -i {{ inventory_dir }}/privatekey.pem cloud@$(terraform output eip_addr | sed 's/\"//g') '\
    source ~/miniforge3/bin/activate rspy && \
    pip install -U pyOpenSSL ecdsa -r ~/rs-infrastructure/collections/kubespray/requirements.txt && \
    cd ~/rs-infrastructure; ansible-galaxy collection install kubernetes.core openstack.cloud && \
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh && \
    curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash && sudo mv ./kustomize /usr/local/bin/ && \
    wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list && \
    sudo apt update && sudo apt install terraform jq -y
    '
  args:
    chdir: roles/terraform/create-cluster/tasks/
    executable: /bin/bash
