commonLabels:
  app.kubernetes.io/instance: "{{ app_name }}"
namespace: logging

helmCharts:
- name: loki-distributed
  repo: https://grafana.github.io/helm-charts
  releaseName: "{{ app_name }}"
  version: 0.78.5
  namespace: logging
  valuesFile: values.yaml


secretGenerator:
  - name: "loki-s3-credentials"
    literals:
      - S3_ACCESS_KEY={{ loki.s3.access_key }}
      - S3_SECRET_KEY={{ loki.s3.secret_key }}
