---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: loki-distributed-query-frontend
  namespace: logging
  labels:
    helm.sh/chart: loki-distributed-0.78.5
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki-distributed
    app.kubernetes.io/version: "2.9.6"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki-distributed
      app.kubernetes.io/instance: loki-distributed
      app.kubernetes.io/component: query-frontend
  maxUnavailable: 3
