---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-distributed-distributor
  labels:
    helm.sh/chart: loki-distributed-0.78.5
    app.kubernetes.io/name: loki-distributed
    app.kubernetes.io/instance: loki-distributed
    app.kubernetes.io/version: "2.9.6"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: distributor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: loki-distributed
      app.kubernetes.io/instance: loki-distributed
      app.kubernetes.io/component: distributor
  endpoints:
    - port: http
      scheme: http
