# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for neuvector.
# This is a YAML-formatted file.
# Declare variables to be passed into the templates.

registry: docker.io
oem: ''
leastPrivilege: false

exporter:
  # If false, exporter will not be installed
  enabled: true
  image:
    repository: neuvector/prometheus-exporter
    tag: latest
  # changes this to a readonly user !
  CTRL_USERNAME: {{ neuvector.core.user2.Fullname }}
  CTRL_PASSWORD: {{ neuvector.core.user2.Password }}
  ctrlSercretName: ''
  enforcerStats:
    enabled: true
  ctrlSecretName: ''
  apiSvc: neuvector-svc-controller-api:10443

  svc:
    enabled: true
    type: ClusterIP
    loadBalancerIP: ''
    annotations: {}
      # service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      # service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "apps-subnet"

  grafanaDashboard:
    enabled: false
    namespace: "" # Release namespace, if empty
    labels: {}
    # annotations: {}
      # k8s-sidecar-target-directory: /tmp/dashboards/neuvector

  serviceMonitor:
    enabled: false
    # labels for the ServiceMonitor.
    labels: {}
    # annotations for the ServiceMonitor.
    annotations: {}
    # Scrape interval. If not set, the Prometheus default scrape interval is used.
    interval: ""
    # MetricRelabelConfigs to apply to samples after scraping, but before ingestion.
    # ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
    metricRelabelings: []
    # RelabelConfigs to apply to samples before scraping
    # ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
    relabelings: []
