# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Secret
metadata:
  name: {{ wazuh.server.user1.secret }}
  labels: 
    app: wazuh-server
type: Opaque
stringData:
  username: kibanaserver
  password: {{ wazuh.server.user1.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ wazuh.server.user2.secret }}
  labels: 
    app: wazuh-server
type: Opaque
stringData:
  username: admin
  password: {{ wazuh.server.user2.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ wazuh.server.user3.secret }}
  labels: 
    app: wazuh-server
type: Opaque
stringData:
  username: {{ wazuh.server.user3.username }}
  password: {{ wazuh.server.user3.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{  wazuh.server.key1.secret }}
  labels: 
    app: wazuh-server
type: Opaque
stringData:
  key: {{ wazuh.server.key1.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ wazuh.agents.key2.secret }}
  labels: 
    app: wazuh-server
type: Opaque
stringData:
  authd.pass: {{  wazuh.agents.key2.authdpass }}