apiVersion: v1
kind: Secret
metadata:
  name: {{ wazuh.server.user1.secret }}
  labels: 
    app: wazuh-server
type: Opaque
stringData:
  username: {{ wazuh.server.user1.username }}
  password: {{ wazuh.server.user1.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ wazuh.server.user2.secret }}
  labels: 
    app: wazuh-server
type: Opaque
stringData:
  username: {{ wazuh.server.user2.username }}
  password: {{ wazuh.server.user2.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ wazuh.server.user3.secret }}
  labels: 
    app: wazuh-server
type: Opaque
stringData:
  username: {{ wazuh.server.user3.username }}
  password: {{ wazuh.server.user3.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{  wazuh.server.key1.secret }}
  labels: 
    app: wazuh-server
type: Opaque
stringData:
  key: {{ wazuh.server.key1.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ wazuh.agents.key2.secret }}
  labels: 
    app: wazuh-server
type: Opaque
stringData:
  authd.pass: {{  wazuh.agents.key2.authdpass }}