namespace: monitoring

commonLabels:
  app.kubernetes.io/instance: "{{ app_name }}"

resources:
  - grafana.yaml
  - podmonitor.yaml
  - image-renderer.yaml

secretGenerator:
- name: grafana-credentials
  literals:
  - GF_SMTP_USER="{{ grafana.smtp_credentials.user }}"
  - GF_SMTP_PASSWORD="{{ grafana.smtp_credentials.password }}"
  - GRAFANA_CLIENT_SECRET="{{ grafana_oidc_client_secret }}"
  options:
    disableNameSuffixHash: true