# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for neuvector.
# This is a YAML-formatted file.
# Declare variables to be passed into the templates.

openshift: false
registry: docker.io
tag: 5.3.2
autoGenerateCert: true
defaultValidityPeriod: 365
internal:
  certmanager:
    enabled: true
    secretname: neuvector-internal

controller:
  enabled: true
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - neuvector-controller-pod
            topologyKey: "kubernetes.io/hostname"

  apisvc:
    type: ClusterIP

  certificate:
    secret:
    keyFile: tls.key
    pemFile: tls.pem
  internal:
    certificate:
      secret: neuvector-internal
      keyFile: tls.key
      pemFile: tls.crt
      caFile: ca.crt

  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  configmap:
    enabled: false
  secret:
    enabled: true
    data:
      oidcinitcfg.yaml:
        Enable: true
        Issuer: {{ kube_oidc_url }}
        group_claim: roles
        Client_ID: {{ neuvector_oidc_client_id }}
        Client_Secret: {{ neuvector_oidc_client_secret }}
        group_mapped_roles:
          - group: admin
            global_role: admin
          - group: default
            global_role: reader
      userinitcfg.yaml:
        users:
        - Fullname: {{ neuvector.core.secops.Fullname }}
          Password: {{ neuvector.core.secops.Password }}
          Role: admin
        - Fullname: {{ neuvector.core.exporter.Fullname }}
          Password: {{ neuvector.core.exporter.Password }}
          Role: reader
        - Fullname: {{ neuvector.core.admin.Fullname }}
          Password: {{ neuvector.core.admin.Password }}
          Role: admin

enforcer:
  enabled: true
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    - effect: NoSchedule
      key: node-role.kubernetes.io/control-plane
  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  internal:
    certificate:
      secret: neuvector-internal
      keyFile: tls.key
      pemFile: tls.crt
      caFile: ca.crt

manager:
  enabled: true
  image:
    repository: neuvector/manager
    hash: sha256:974dcacd6d13a1a9ee04b5cc60d3c0c6c3a4617e6a091c745c65280cb25d50cf
  svc:
    type: ClusterIP
  certificate:
    secret:
    keyFile: tls.key
    pemFile: tls.pem
  ingress:
    enabled: true
    host: neuvector.{{ platform_domain_name }}
    ingressClassName: "nginx"
    path: "/"
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    tls: true
    secretName: neuvector-{{ platform_domain_name | replace(".", "-") }}
  resources:
    limits:
      cpu: 400m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: "node-role.kubernetes.io/infra"
              operator: Exists

cve:
  adapter:
    enabled: false
  updater:
    enabled: true
  scanner:
    enabled: true
    replicas: 3
    resources:
      limits:
        cpu: 400m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 1Gi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "node-role.kubernetes.io/infra"
                operator: Exists
    runAsUser:
    internal:
      certificate:
        secret: neuvector-internal
        keyFile: tls.key
        pemFile: tls.crt
        caFile: ca.crt

resources:
  limits:
    cpu: 400m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi

runtimePath: /var/run/docker.sock

admissionwebhook:
  type: ClusterIP

crdwebhook:
  enabled: false
  type: ClusterIP
