# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package_paths:
- apps

# TODO:
# Clean unused secrets here and in realmimport 
grafana_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
graylog_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
kibana_processing_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
kibana_security_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
kubectl_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
linkerd_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
prometheus_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
thanos_oidc_client_key: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
oauth2_proxy_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
jupyterhub_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
apikeymanager_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
apikeymanager_cookieSecret: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters') }}"
# https://oauth2-proxy.github.io/oauth2-proxy/configuration/overview/#generating-a-cookie-secret
oauth2_proxy_cookieSecret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') | b64encode }}"
neuvector_oidc_client_secret: "{{ lookup('password', '/dev/null length=60 chars=ascii_letters') }}"
rsserver_cookieSecret: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters') }}"

apikeymanager:
  database:
    name: apikeymanagerdb
    host: postgresql-cluster-rw.database.svc.cluster.local
    username: apikeymanager
    password: "{{ lookup('password', '/dev/null length=30 chars=ascii_letters') }}"
    secret: apikeymanager-database-password

certmanager:
  clusterissuer:
    acme:
      email: user@example.com

grafana:
  # Configure here additional plugins to install in Grafana
  # The url must point to a ZIP filed, not necessarily signed
  # The name must be the plugin ID
  # Leave [] if you don't want to install any plugins
  custom_plugins: []
    # - name: ""
    #   url: ""
  smtp:
    enabled: "true"
    from_address: test@example.com
    from_name: Test
    host: HOST
  smtp_credentials:
    password: PASSWORD
    user: test@example.com
  serviceMonitor:
    interval: 30s
    scrapeTimeout: 10s

postgresql:
  postgres_user:
    password: "{{ lookup('password', '/dev/null length=30 chars=ascii_letters') }}"
  replication_password: "{{ lookup('password', '/dev/null length=30 chars=ascii_letters') }}"
  replication_user: "{{ lookup('password', '/dev/null length=30 chars=ascii_letters') }}"
  bucket: "{{ cluster_name }}-psql"

keycloak:
  image: quay.io/keycloak/keycloak:23.0.6
  operator:
    image: quay.io/keycloak/keycloak-operator:23.0.6
  database: 
    host: postgresql-cluster-rw.database.svc.cluster.local
    name: keycloak
    username: keycloak
    password: "{{ lookup('password', '/dev/null length=30 chars=ascii_letters') }}"
    secret: keycloak-database-password
  serviceMonitor:
    interval: 30s
    scrapeTimeout: 10s
  replicaCount: 1
  proxy:
    mode: passthrough
  logLevel: info
  realm:
    name: rspy

prefect:
  database:
    host: postgresql-cluster-rw.database.svc.cluster.local
    username: prefect
    password: "{{ lookup('password', '/dev/null length=30 chars=ascii_letters') }}"
    name: prefect
    secret: prefect-database-password

prefectworker:
  name: on-demand-k8s-pool
  number: 2

prefect3:
  database:
    host: postgresql-cluster-rw.database.svc.cluster.local
    username: prefect3
    password: "{{ lookup('password', '/dev/null length=30 chars=ascii_letters') }}"
    name: prefect3
    secret: prefect3-database-password
  block_auth: auth
  block_s3: user-s3

prefect3worker:
  staging:
    name: staging-prefect-pool
    number: 2
  eopf:
    name: eopf-prefect-pool
    number: 2

rs_server_catalog:
  database:
    host: rs-server-catalog-db.database.svc.cluster.local
    name: catalog
    password: password
    username: postgres

rs_server:
  database:
    host: postgresql-cluster-rw.database.svc.cluster.local
    name: rspydemo
    password: test
    username: test
    secret: status-database-password

rs_server_staging:
  # This token must be generated from https://processing.{{ platform_domain_name }}/jupyter/hub/token
  # See Prerequisite in the [Dask Gateway how-to](/docs/how-to/dask-gateway.md).
  jupyterhub_token: <REPLACE_WITH_TOKEN_GENERATED_FROM_JUPYUTER>

rs_server_station_credentials:
  adgs:
    username: test
    password: test
    client_id: client_id
    client_secret: client_secret
  adgs2:
    username: test
    password: test
    client_id: client_id
    client_secret: client_secret
  cadip:
    username: test
    password: test
    client_id: client_id
    client_secret: client_secret
  ins:
    username: test
    password: test
    client_id: client_id
    client_secret: client_secret
  mps:
    username: test
    password: test
    client_id: client_id
    client_secret: client_secret
  mti:
    username: test
    password: test
    client_id: client_id
    client_secret: client_secret
  nsg:
    username: test
    password: test
    client_id: client_id
    client_secret: client_secret
  sgs:
    username: test
    password: test
    client_id: client_id
    client_secret: client_secret
  lta:
    username: test
    password: test
    client_id: client_id
    client_secret: client_secret
  s1a:
    username: test
    password: test
    client_id: client_id
    client_secret: client_secret
  s2a:
    username: test
    password: test
    client_id: client_id
    client_secret: client_secret

neuvector:
  core:
    admin:
      Fullname: "admin"
      Password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1, override_special='!#$%&*()-_=+[]{}<>:?', length=30) }}"
    exporter:
      Fullname: "exporter"
      Password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1, override_special='!#$%&*()-_=+[]{}<>:?', length=30) }}"
    secops:
      Fullname: "rspysecopsadm"
      Password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1, override_special='!#$%&*()-_=+[]{}<>:?', length=30) }}"
    secret: neuvector-init
  exporter:
    host: neuvector-controller-api.svc.cluster.local
    CTRL_USERNAME: exporter
    CTRL_PASSWORD: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1, override_special='!#$%&*()-_=+[]{}<>:?', length=30) }}"
    secret: exporter

wazuh:
  server:
    kibanaserver:  
      username: "kibanaserver"
      password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1, override_special='!#$%&*()-_=+[]{}<>:?', length=30) }}"
      secret: dashboard-cred
    admin: 
      username: "admin"              
      password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1, override_special='!#$%&*()-_=+[]{}<>:?', length=30) }}"
      secret: indexer-cred
    api: 
      username: "wazuh-wui"
      password: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_special=1, min_numeric=1, override_special='!#$%&*()-_=+[]{}<>:?', length=30) }}"
      secret: wazuh-api-cred
    clusterkey:
      key: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_numeric=1, special=false, length=32) }}" 
      secret: wazuh-cluster-key
  agents:
    authd: 
      authdpass: "{{ lookup('community.general.random_string', min_lower=1, min_upper=1, min_numeric=1, special=false, length=14) }}" 
      secret: wazuh-authd-pass
# TODO : move to wazuh part 
wazuh_url: WAZUH_URL
wazuh_saml_client_id: WAZUH_SAML_CLIENT_ID
wazuh_saml_client_key: WAZUH_SAML_CLIENT_KEY

rspy:
  tmp_bucket: "{{ cluster_name }}-temp"
  catalog_bucket: "{{ cluster_name }}-catalog"

loki:
  retention: 1460h
  bucket: "{{ cluster_name }}-loki"

grafanatempo:
  metaMonitoring:
    serviceMonitor: 
      interval: 30s  
      scrapeTimeout: 10s
  s3:
    bucket: "{{ cluster_name }}-tempo"

velero:
  bucket:  "{{ cluster_name }}-velero"
  bckStorageLoc:
    name:  "{{ cluster_name }}-velero"
  volSnapLoc:
    name: aws-default

jupyterhub:
  services:
    daskgateway:
      apitoken: "{{ lookup('password', '/dev/null', length=64, chars=['ascii_letters']) }}"
      apiurl: http://hub.processing.svc.cluster.local:8081/api
    metrics:
      apitoken: "{{ lookup('password', '/dev/null', length=64, chars=['ascii_letters']) }}"

# You might need to create a docker registry secret
# to retrieve private container image from the
# GitHub Container Registry : ghcr.io
# Refer to the doc in /docs/how-to/GitHub Container Registry.md
github:
  registrySecret:
    name: ghcr-k8s
    registry: ghcr.io
    username: YOUR_GITHUB_USERNAME
    password: YOUR_GITHUB_TOKEN

# To use the vault the first time you have
# to manually create an empty secret named 
# generated_inventory_vars in the vault UI
# and set the upload_existing to false and upload_backup to true
vault:
  # Download the inventory from the vault 
  download_inventory_vars: false
  # Path to the inventory in the vault ending without "/"
  path: null
  # Token to access the vault
  token: null
  # Upload newly generated inventory to the vault
  upload_backup: false
  # Upload existing inventory to the vault
  upload_existing: false
  # URL of the vault
  url: https://vault.coprs.esa-copernicus.eu
