kubelet_rotate_server_certificates: true
kube_proxy_metrics_bind_address: 0.0.0.0:10249
kubelet_config_extra_args:
  # cf: https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies
  cpuManagerPolicy: static
kube_kubeadm_controller_extra_args:
  use-service-account-credentials: true
kube_apiserver_enable_admission_plugins: [NodeRestriction]

dns_mode: coredns
resolvconf_mode: host_resolvconf
nameservers:
  - 100.125.0.41
  - 100.126.0.41
upstream_dns_servers:
  - 100.125.0.41
  - 100.126.0.41
coredns_external_zones:
- zones:
  - prod-cloud-ocb.orange-business.com
  nameservers:
  - 100.125.0.41
  - 100.126.0.41
nodelocaldns_external_zones:
- zones:
  - prod-cloud-ocb.orange-business.com
  nameservers:
  - 100.125.0.41
  - 100.126.0.41
