# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Create registry
  shell: |
    set -o allexport; source {{ inventory_dir }}/.env; source {{ inventory_dir }}/openrc.sh; set +o allexport; terraform apply -auto-approve -var-file="{{ inventory_dir }}/cluster.tfvars"
  args:
    chdir: roles/terraform/registry/tasks/
    executable: /bin/bash
  tags: create

- name: Get registry url from terraform output
  shell: |
    set -o allexport; source {{ inventory_dir }}/.env; source {{ inventory_dir }}/openrc.sh; set +o allexport; terraform output -raw registry-url
  register: registry_url
  args:
    chdir: roles/terraform/registry/tasks/
    executable: /bin/bash

- name: Get registry username from terraform output
  shell: |
    set -o allexport; source {{ inventory_dir }}/.env; source {{ inventory_dir }}/openrc.sh; set +o allexport; terraform output -raw user
  register: registry_user
  args:
    chdir: roles/terraform/registry/tasks/
    executable: /bin/bash

- name: Get registry password from terraform output
  shell: |
    set -o allexport; source {{ inventory_dir }}/.env; source {{ inventory_dir }}/openrc.sh; set +o allexport; terraform output -raw password
  register: registry_pass
  args:
    chdir: roles/terraform/registry/tasks/
    executable: /bin/bash

- name: Configure Harbor Proxy Cache Registry
  #hosts: localhost
  gather_facts: no
  vars:
    harbor_url: "{{ registry_url.stdout }}"
    harbor_user: "{{ registry_user.stdout }}"
    harbor_pass: "{{ registry_pass.stdout }}"
    #dockerhub_user: "your_dockerhub_username"
    #dockerhub_pass: "your_dockerhub_password"
    #proxy_project_name: "proxy-cache-project"

  tasks:
    - name: Create registry endpoint
      ansible.builtin.uri:
        url: "{{ harbor_url }}/api/v2.0/registries"
        method: POST
        user: "{{ harbor_user }}"
        password: "{{ harbor_pass }}"
        force_basic_auth: true
        body_format: json
        body:
          name: "dockerhub"
          type: "docker-hub"
          url: "https://registry-1.docker.io"
          access_id: "{{ dockerhub_user }}"
          access_secret: "{{ dockerhub_pass }}"
        status_code: 201
      register: registry_creation

    - name: Get registry ID
      ansible.builtin.uri:
        url: "{{ harbor_url }}/api/v2.0/registries?q=name%3Ddockerhub"
        method: GET
        user: "{{ harbor_user }}"
        password: "{{ harbor_pass }}"
        force_basic_auth: true
        return_content: true
        status_code: 200
      register: registry_query

    - name: Extract registry ID
      set_fact:
        registry_id: "{{ (registry_query.content | from_json)[0].id }}"

    - name: Create proxy cache project
      ansible.builtin.uri:
        url: "{{ harbor_url }}/api/v2.0/projects"
        method: POST
        user: "{{ harbor_user }}"
        password: "{{ harbor_pass }}"
        force_basic_auth: true
        body_format: json
        body:
          project_name: "proxycache"
          public: false
          registry_id: "{{ registry_id }}"
          proxy_cache: true
        status_code: 201
      register: proxy_project_creation
