commonLabels:
  app.kubernetes.io/instance: "{{ app_name }}"

resources:
  - ns-database.yaml
  - ns-iam.yaml
  - ns-infra.yaml
  - ns-logging.yaml
  - ns-monitoring.yaml
  - ns-networking.yaml
  - ns-processing.yaml
  - ns-security.yaml
