apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
spec:
  selector:
    matchLabels:
      app: ewazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
    spec:
      hostPID: true
      hostNetwork: true
      containers:
      - name: wa-main-container
        image: wazuh-agent-installer:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          runAsNonRoot: true
          runAsUser: 1230 # Specify the non-root user ID
          runAsGroup: 3450 # Specify the non-root group ID
      initContainers:
      - name: wa-init-container
        image: wazuh-agent-installer:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          runAsUser: 0
        
                        