apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wazuh

configMapGenerator:
  - name: wa-script-configmap
    files:
      - wazuh-agent_install.sh

  - name: wa-alpine-configmap
    files: 
      - wazuh-alpine-apk.sh