# Copyright 2023-2025 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check code quality

on:
  push:
    branches:
      - develop # pushes on the 'develop' branch
    tags:
      - '**' # new git tags (including hierarchical tags like v1.0/beta)
  pull_request:
    types: [opened, synchronize, reopened]
    # run this worflow only for code/test related changes (avoid it for documentation)
    paths: ['**.py', '**.sh', '**.yaml', '**.yml']
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      code: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code: ['**.py', '**.yaml', '**.yml']

  check-license:
    runs-on: ubuntu-latest
    name: Check copyright license headers
    needs: changes
    permissions:
      contents: write
      pull-requests: write
    if: ${{ needs.changes.outputs.code == 'true' }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: check License Header
        uses: apache/skywalking-eyes/header@main
        with:
          log: debug
          mode: check
